### ISSUE TITLE
Ornementations doesn't work

### ISSUE THREAD

**Issue by katagen** [xcaeag/Dem-Slicer-Qgis-Plugin#2]
I'm trying to use this nice plugin, but I can easily have a 'DEM slicer', but when I want one with ornementation with the peaks name, it doesn't works.
I have the DEM slicer, but not the ornementation. And when I look at the progression bar, it stays at 58%, even after 2 hours (even on a small area with only 3 peaks)?!?

I have DEM Slicer v0.3 and QGIS 3.16.

**Comment by xcaeag** [comment]
it's strange, I just had the same problem, with polygons, but in version 0.4.

0.4 has just been released and brings many improvements, notably in ergonomics, but requires QGis 3.20.

it's going to be difficult for me to fix v0.3. Is the bug reproduced with a reduced number of points? 150 points are projected in a few seconds on my computer (after a few minutes, you can kill QGis!). Maybe there are projection issues, try working with layers of the same projection system...

**Comment by katagen** [comment]
All the layers (MNT/DEM, point layer) are in the same projection (epsg: 2056).
I have tried with only 3 peaks (points)!!!

**Comment by xcaeag** [comment]
yes, it's not normal.. but I have no ideas now !
A test works for me, in your projection, with v0.3 (peaks from osm).

**Comment by katagen** [comment]
Solved! It doesn't accept a point layer with Z value!

**Comment by xcaeag** [comment]
Thanks, I hadn't thought of that.
z accepted in v0.4, and don't forget, the new version fixes a lot of anomalies in the calculations...
